<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="cTrader.Automate" Version="*"/>
        <PackageReference Include="cTrader.Automate.SourceGenerators" Version="*"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="config.json"/>
    </ItemGroup>
</Project>
